### ISSUE TITLE
Provide a JSON schema for auto-completion in checkstyle.json

### ISSUE THREAD

**Issue by Gama11** [vshaxe/vscode-checkstyle#11] opened 2018-05-20 17:44 UTC
Right now configuration is a bit tedious due to the lack of auto-completion. VSCode extension can contribute a JSON schema that allows this. I've used this before to generate a schema for `vshaxe-build.json` files in the vshaxe-build extension:

- https://github.com/vshaxe/vshaxe-build/blob/031fccbd43cdb8b8210f75dbc19a6f3332d929fa/package.json#L38-L48
- https://github.com/vshaxe/vshaxe-build/blob/master/schemas/vshaxe-build-schema.json

The schema was auto-generated from the Haxe type definitions using @nadako's (not-quite-finished) library: https://github.com/nadako/haxe-type-to-json-schema

@AlexHaxe interested in working on this? :)

**Comment by AlexHaxe** [comment] 2018-05-21 08:51
I guess ultimately that should be something derived from checkstyle's code.

I am not sure if and how JSON schema would handle checkstyle's json format since our check definition looks like this:
```
{
    "props": {
        "max": 2000
    },
    "type": "FileLength"
},
{
    "props": {
        "option": "upperCase"
    },
    "type": "HexadecimalLiteral"
},
```
where the value of `type` defines what `props` you can set.

**Comment by Gama11** [comment] 2018-05-21 10:33
Hm.. good question, would have to look into that.

Honestly, if it can't be properly described with a JSON schema, it might be worth designing a better "version 2" of the config file, because auto-completion is kind of a big deal. :) (while keeping backwards-compatibility with the old one of course)

**Comment by AlexHaxe** [comment] 2018-05-22 09:38
So what you are proposing is a config structure like this:
```
    "checks": [{
            "EmptyBlock": {
                "tokens": [
                    "IF"
                ],
                "option": "stmt"
            }
        },
        {
            "Indentation": {
                "character": "    ",
                "conditionalPolicy": "fixed_zero",
                "wrapPolicy": "none"
            }
        },
        {
            "Indentation": {
                "wrapPolicy": "larger"
            }
        }
    ],
```
I guess that could work, but right now I can't see how I can build a typed data structure that can hold all of it and still produce the above output with a simple `Json.stringify` call - preferably without handcrafting it.

Keep in mind: we need the ability to have multiple instances of some checks, because e.g. they apply different policies to different tokens, so an alternative could look like that:
```
    "checks": {
        "EmptyBlock": [{
            "tokens": [
                "IF"
            ],
            "option": "stmt"
        }],
        "Indentation": [{
            "character": "    ",
            "conditionalPolicy": "fixed_zero",
            "wrapPolicy": "none"
        },
	{
            "wrapPolicy": "larger"
        }]
    }
```
where each check has 1-n property definitions.
But the general problem of variable field names and typing remains.

**Comment by Gama11** [comment] 2018-05-22 13:20
Actually, I think the original config _can_ be properly expressed with a JSON schema. Check this out:

![](https://i.imgur.com/JHy7vvB.gif)

```json
"haxecheckstyle.config": {
	"properties": {
		"checks": {
			"anyOf": [
				{
					"type": "object",
					"properties": {
						"type": {
							"type": "string",
							"enum": [
								"FileLength"
							]
						},
						"props": {
							"type": "object",
							"properties": {
								"max": {
									"type": "integer"
								}
							}
						}
					}
				},
				{
					"type": "object",
					"properties": {
						"type": {
							"type": "string",
							"enum": [
								"HexadecimalLiteral"
							]
						},
						"props": {
							"type": "object",
							"properties": {
								"option": {
									"type": "string",
									"enum": [
										"upperCase",
										"lowerCase"
									]
								}
							}
						}
					}
				}
			]
		}
	}
},
```

**Comment by AlexHaxe** [comment] 2018-05-22 13:29
> Actually, I think the original config can be properly expressed with a JSON schema. 

ok, so we don't need a version 2 after all... just someone who knows JSON schemas better than me :)

So we are back to the question how to generate a schema without too much manual work, something that automatically includes new checks and properties. Maybe with a manual version bump.

**Comment by AlexHaxe** [comment] 2018-06-05 22:17
That's some of the most complex macro work I've done so far. I had to change @nadako's code from a macro generating a schema object to a macro that builds an expression that generates a schema object. Mainly because we use a lot of abstract enums in our configuration, and there seemed to be no other way to get at their values. It remains to be seen if the new Haxe 4 abstract enums change that.

Currently schema generation only runs on Haxe 3.4.7 (or lower, i guess).

There's probably ways to optimise or simplify my code, but for now it seems to works. 

Checkstyle uses two config files with default names: `checkstyle.json` and `checkstyle-exclude.json`.
Technically `checkstyle.json` includes `checkstyle-exclude.json` but the schemas don't reference each other. I might change that in the future, for now `checkstyle-schema.json` contains a duplicate of `checkstyle-excludes-schema.json`.

**Comment by Gama11** [comment] 2018-06-05 22:25
Wow, nice, I'll have to check that out when I get a chance. 👍 Pull request adding the schemas for VSCode completion incoming? ;)

>It remains to be seen if the new Haxe 4 abstract enums change that.

Right now, the `enum abstract` syntax is just that.. syntactic sugar. It even still uses the old `@:enum` metadata under the hood I think.

**Closed as completed** 2018-06-06 21:32 UTC
Labels: enhancement
